name: Build and publish Docker image

on:
  push:
    branches:
      - main  # Replace with the branch(es) you want this action to trigger on.

jobs:
  docker:
    name: "prime_${{ matrix.tag }}"
    runs-on: ubuntu-latest # Running on Ubuntu is fine here for most use cases.
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 21
          - 17
          - 15
          - 13
          - 11
          - 8
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./${{ matrix.tag }}/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/virtualwinter/azul-prime-pterodactyl:azul-prime_${{ matrix.tag }}

